module.exports={
    burgerMenu(){
    this.clickBurgerMenu()
    this.clickAllItems()
    this.clickAbout()
    this.clickLogout()
    this.clickResetAppState()
    this.clickLogout()
  },
  clickBurgerMenu(){
  cy.get('[id="react-burger-menu-btn"]')
    .click()
  },
  clickAllItems(){
  cy.get('[id="inventory_sidebar_link"]')
    .click()
  },
  clickAbout(){
    cy.get('[id="about_sidebar_link"]')
      .click()
  },
  clickLogout(){
    cy.get('[id="logout_sidebar_link"]')
      .click()
  },
  clickResetAppState(){
    cy.get('[id="reset_sidebar_link"]')
      .click()
  },
  clickLogout(){
    cy.get('[id="logout_sidebar_link"]')
      .click()
}
}

